name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

env:
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
  SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
  SONATYPE_KEY: ${{ secrets.SONATYPE_KEY }}
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'djai-app'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
