name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'DJetCloud'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: SONATYPE_USER=${{ secrets.SONATYPE_USER }} SONATYPE_KEY=${{ secrets.SONATYPE_KEY }} ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
